### ISSUE TITLE
install ERROR

### ISSUE THREAD

**Issue by guoyuh** [miwipe/ngsLCA#29]
hi:
    thanks for  ngsLCA
    but i get a error when Install the package "ngsLCA" with the command devtools::install_github("wyc661217/ngsLCA").
    ERROR: dependencies ‘ComplexHeatmap’, ‘ggpubr’, ‘vegan’ are not available for package ‘ngsLCA’,my R version is latest  4.2.0

**Comment by miwipe** [comment]
hi, 

Could you tell what system you are running and how you installed R? This would help us recreating your error. If you installed R using conda with r-essentials then this might be problematic for some of these packages.

**Comment by guoyuh** [comment]
hi,
my system is  Ubuntu 18.04.4  , i'm surely my R is not from conda ,but is from system  '/usr/bin/R' ,R version is the latest 4.2.1

**Comment by miwipe** [comment]
I am sorry but i don't have an ubuntu installation available to test it. But the programme installs nicely on my unix and linux systems.
