### ISSUE TITLE
problems running the test data

### ISSUE THREAD

**Issue by slennart** [miwipe/ngsLCA#30]
I've been having problems running ngsLCA on my own data so I tried running the test data first, but I also can't get that to work. I downloaded SPL_015_1444.fq.plastids.bam from ERDA, downloaded the ncbi tax_tax_dmp and then ran the following code:

`ngsLCA -editdistmin 0 -editdistmax 0 -names ncbi_tax_dmp/names.dmp -nodes ncbi_tax_dmp/nodes.dmp -acc2tax ncbi_tax_dmp/nucl_gb.accession2taxid.gz -bam SPL_015_1444.fq.plastids.bam -outnames outfile.ed0 `

**Comment by slennart** [comment]
![ngsLCA_error2](https://user-images.githubusercontent.com/115784342/208616665-ddfacc08-5b65-4068-b632-031b9fd3e6ac.PNG)

**Comment by miwipe** [comment]
Hi slennart, 

Running the latest version of the ngsLCA with the command you provided and downloading the file again as well as the ncbi taxonomy, gives me no errors. Could you check you have downloaded the file correctly, have the recent version of ngsLCA and ncbi taxonomy. Another thing is that the bam/sam files have to be sorted by coordinate e.g. readID. 

Mikkel

<img width="1724" alt="Screenshot 2023-01-05 at 11 35 30" src="https://user-images.githubusercontent.com/11410192/210760160-82204e2c-d6c5-4813-90c6-380be2d783b4.png">
