### ISSUE TITLE
ngsLCA with bwa output

### ISSUE THREAD

**Issue by tothuhien** [miwipe/ngsLCA#31]
Hi,
I'm wondering if it's ok to run ngsLCA with the bam file from bwa-mem. I see in the tutorial using bowtie2 with some specific parameters. If we use bwa-mem, is there any option that are recommended.
Thanks,
Hien

**Comment by miwipe** [comment]
Hi Hien,

BWA-MEM bam files should also be supported. I suggest you look into BWA-MEM and set options according to your study.

Cheers,
Mikkel



Dr. Mikkel Winther Pedersen
Assistant professor
The Globe Institute
University of Copenhagen
Oester Voldgade 5-7
1350 Cph C
Denmark

Phone: +45 2927 5342
Mail: ***@***.***
Skype: mikkelwintherpedersen

On 2 Nov 2023, at 14.32, Thu-Hien To ***@***.***> wrote:



Hi,
I'm wondering if it's ok to run ngsLCA with the bam file from bwa-mem. I see in the tutorial using bowtie2 with some specific parameters. If we use bwa-mem, is there any option that are recommended.
Thanks,
Hien

**Comment by tothuhien** [comment]
Thanks for your prompt response!
