### ISSUE TITLE
Error in MN:i: parsing sequences with MN:i:1 and above have been parsed? 

### ISSUE THREAD

**Issue by miwipe** [miwipe/ngsLCA#6]
see below parsed seqs which doesn't fit 100% to reference sequence

samtools view CHL_155_12485.sort.bam | grep  -e 'HISEQ:50:C6NJJANXX:1:1108:14286:4677' -e 'HISEQ:50:C6NJJANXX:1:1108:14285:32643' -e 'HISEQ:50:C6NJJANXX:1:1108:14287:23673' -e 'HISEQ:50:C6NJJANXX:1:1108:14289:31539' -e 'HISEQ:50:C6NJJANXX:1:1108:14289:54817' | less -S

**Comment by ANGSD** [comment]
is fixed
